AWSTemplateFormatVersion: 2010-09-09

Mappings:
  MyRegionMap:
    eu-west-1:
      HVM64: ami-071f4ce599deff521
    eu-west-2:
      HVM64: ami-0e49551fc78560451
Parameters:
  MyKeyName:
    Description: Select the key name from the list
    Type: String
    Default: MyKeyPairLondin
    AllowedValues:
      - MyKeyPairLondin
  MyInstanceType:
    Description: Select the InstanceType from the list
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
      - t2.small
  MyAvailabilityZone:
    Description: Select the Az
    Type: String
    Default: eu-west-2a
    AllowedValues:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MySG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0